# Generated by Django 4.0.6 on 2023-01-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField()),
                ('email_user', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('tel', models.CharField(default='------------', max_length=20)),
            ],
        ),
    ]
