# Generated by Django 4.0.6 on 2023-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='image_article')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
