# Generated by Django 4.0.6 on 2023-01-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_content_alter_section_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section_post',
        ),
    ]
